### PR TITLE
trying out pre-commit hooks

### PR DESCRIPTION
**Pull request by sblack4**
what do you think of pre-commit hooks?

### CODE REVIEW

**Comment by sblack4** [comment]
The GitHub action does largely the same thing, I just hate when I commit something and then realize that it's not properly formatted

**Comment by smiller171** [comment]
I like pre-commit hooks a lot, I just wish git would natively sync them to the repo so we wouldn't need to lean on external tools.

I also often set up VSCode to run anything I'd put in a pre-commit hook on every save. We could lean on VSCode Remote to share these setups.

**Review by smiller171 — APPROVED** [review]
lgtm

**Comment by sblack4** [comment]
VSCode Remote sounds pretty dope. Have you used it much?

**Comment by smiller171** [comment]
Yeah I've used it a decent amount. I kinda wanna set up VSCode Remote container configs for everything at some point. So far I haven't because it messes with my ability to sign commits with my Yubikey. I'll probably end up just using an on-device gpg key

**Pull request merged**
